site_name: Proyecto MKDOCS
site_author: Iñigo Duran Sanz
site_url: https://inigompare.github.io/Proyecto-MKDOCS/
repo_url: https://github.com/inigompare/Proyecto-MKDOCS

# 1. Configuración del Tema
theme:
  name: material
  language: es
  palette:
    primary: deep purple
    accent: teal
  features:
    - content.code.copy

# 2. Extensiones
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

# 3. Barra de Navegación
nav:
  - Inicio: index.md
  - Introducción: introduccion.md
  - Requisitos Previos: requisitos.md
  - Configuración: configuracion.md
  - Conclusiones: conclusiones.md
